apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflixyass-deployment
  labels:
    app: netflixyass
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflixyass
  template:
    metadata:
      labels:
        app: netflixyass
    spec:
      containers:
      - name: netflixyass
        image: registry.gitlab.com/benabbes.mohamedaziz30/jenkinstest/netflixyass:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: netflixyass-service
  labels:
    app: netflixyass
spec:
  type: ClusterIP
  selector:
    app: netflixyass
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netflixyass-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: www.netflix-mohamed-aziz-benabbes.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: netflixyass-service
            port:
              number: 80
